"""empty message

Revision ID: 1da28536556f
Revises: 89b049015823
Create Date: 2023-11-20 15:00:01.732402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da28536556f'
down_revision = '89b049015823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('userName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userName', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
