"""empty message

Revision ID: 4258e7e01fa1
Revises: 217f36636a82
Create Date: 2023-11-16 21:44:38.281612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4258e7e01fa1'
down_revision = '217f36636a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posterPath', sa.String(length=120), nullable=False))
        batch_op.drop_column('poster_path')

    with op.batch_alter_table('favorite_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posterPath', sa.String(length=80), nullable=False))
        batch_op.drop_column('poster_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_path', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('posterPath')

    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_path', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('posterPath')

    # ### end Alembic commands ###
