"""empty message

Revision ID: 473c53b90c73
Revises: 2d5cf4dc0c93
Create Date: 2023-12-06 16:10:32.642613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473c53b90c73'
down_revision = '2d5cf4dc0c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('targetName', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('targetPoster', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('targetPoster')
        batch_op.drop_column('targetName')

    # ### end Alembic commands ###
