"""empty message

Revision ID: 57555bcc2245
Revises: 620b19121d55
Create Date: 2023-11-10 18:44:48.072669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57555bcc2245'
down_revision = '620b19121d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=80), nullable=False))

    with op.batch_alter_table('favorite_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_series', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
