"""empty message

Revision ID: 583cb50bb994
Revises: 57555bcc2245
Create Date: 2023-11-16 20:06:21.524144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583cb50bb994'
down_revision = '57555bcc2245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('poser_path', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('runtime', sa.Integer(), nullable=False))

    with op.batch_alter_table('favorite_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('poser_path', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('runtime', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_series', schema=None) as batch_op:
        batch_op.drop_column('runtime')
        batch_op.drop_column('poser_path')
        batch_op.drop_column('title')

    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.drop_column('runtime')
        batch_op.drop_column('poser_path')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
