"""empty message

Revision ID: 8cf33903b10b
Revises: 473c53b90c73
Create Date: 2023-12-06 16:11:10.012678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf33903b10b'
down_revision = '473c53b90c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('targetName',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('targetPoster',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('targetPoster',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('targetName',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
