"""empty message

Revision ID: acf98f56f390
Revises: 20e32a056bd1
Create Date: 2023-11-03 23:32:45.668354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf98f56f390'
down_revision = '20e32a056bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_firstName_key', type_='unique')
        batch_op.drop_constraint('user_lastName_key', type_='unique')
        batch_op.drop_column('confirmPassword')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmPassword', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_lastName_key', ['lastName'])
        batch_op.create_unique_constraint('user_firstName_key', ['firstName'])

    # ### end Alembic commands ###
