"""empty message

Revision ID: dad580947f96
Revises: 4258e7e01fa1
Create Date: 2023-11-16 21:48:43.965024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad580947f96'
down_revision = '4258e7e01fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster', sa.String(length=120), nullable=False))
        batch_op.drop_column('posterPath')

    with op.batch_alter_table('favorite_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster', sa.String(length=80), nullable=False))
        batch_op.drop_column('posterPath')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posterPath', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('poster')

    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posterPath', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('poster')

    # ### end Alembic commands ###
