"""empty message

Revision ID: f79ae5bd7c3d
Revises: d7fff657be1c
Create Date: 2023-11-03 21:48:58.515029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79ae5bd7c3d'
down_revision = 'd7fff657be1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_confirm_password_key', type_='unique')
        batch_op.drop_constraint('user_password_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_password_key', ['password'])
        batch_op.create_unique_constraint('user_confirm_password_key', ['confirm_password'])

    # ### end Alembic commands ###
